require('dotenv').config();

const Consent = require('../models').Consent;
const token = require('../Controller/token_control');
const Log = require('../models').Log;
const { Op } = require("sequelize");
const multer = require('multer');
const multerS3 = require('multer-s3');
const aws = require('aws-sdk');


aws.config.update({
    accessKeyId : process.env.ACCESS_KEY ,
    secretAccessKey : process.env.SECRET_ACCESS_KEY
});

const s3 = new aws.S3({
    params: { Bucket: 'ait-placements'},
    region: 'us-east-1',
})


exports.createConsent = async function(req,res){
    try{
        const data = {
            RequesterAadhar: req.body.RequesterAadhar,
            ApproverAadhar: req.body.ApproverAadhar,
            Status: req.body.Status,
            attachment: req.body.attachment
        }

        const new_consent = await Consent.create(data);

        if(new_consent == null)
            res.send({error:'Server Error.Try Again'});
        else
        {
            const log_data = {
                ConsentID : new_consent.ConsentID,
                Action : 'Consent Request Generated by User. Pending from approver'
            }

            await Log.create(log_data);
            await token.sendNotification(ApproverAadhar,"Someone requested for your address");
            res.send({ID:new_consent.ConsentID,message:'Consent Generated Successfully'});
        }    

    }catch(err){
        console.log("Error while creating consent",err);
        res.send({ error : 'Server Error.Try Again'});
    }
}

exports.updateConsent = async function(req,res){
    try{
        const data = {
            Status:req.body.Status
        }

        const result = await Consent.update(data,{
            where : {
                ConsentID : req.body.ConsentID
            }
        });

        if(result == null)
            res.send({error:'Server Error.Try Again'});
        else
        {
            let new_action;
            if(req.body.Status == 'Approved')
            {
                new_action = 'Consent Approved by approver';
                await token.sendNotification(result.RequesterAadhar,"Your Consent Approved by landlord");
            }
            else if(req.body.Status == 'Reviewed')
            {    
                new_action = 'Approved Address Reviewed by User';
                await token.sendNotification(result.ApproverAadhar,"Consent approved by you is Reviewed by the user.See Final Address");
            }    
            else if(req.body.Status == 'Finish')
                new_action = 'Process Complete';
            
            const log_data = {
                ConsentID : req.body.ConsentID,
                Action : new_action
            }

            await Log.create(log_data);
            
            res.send({message:'Status Updated successfully'});
        }    
    }catch(err){
        console.log("Error while updating consent",err);
        res.send({ error : 'Server Error.Try Again'});
    }
}

exports.getConsentDetails = async function(req,res){
    try{
        const data = await Consent.findAll({where:{
            [Op.or]:[
                {RequesterAadhar : req.body.aadhar},
                {ApproverAadhar : req.body.aadhar}]
        }})

        res.send(data);
    }catch(err){
        console.log("Error while retreiving consent details",err);
        res.send({ error : 'Server Error.Try Again'});
    }
}

exports.upload = multer({

    storage: multerS3({
        s3: s3,
        bucket: 'ait-placements',
        key: async function (req, file, cb) {
            
            let x = await authenticate(req);
            
            if(!x)
                return res.status(401).send('unauthorized');
    
            try{
                //console.log(file);
                cb(null, (Date.now()).toString() + file.originalname) ;
            }catch(err){
                // console.log(err);
            }     
        }
    })
});
